// src/utils/converter.js

/**
 * EMRO HTML → 신버전 변환기 (규칙 기반)
 * 현재까지 학습한 컨버전 규칙들을 자동으로 적용
 */

export function convertFile(inputHtml) {
  let output = inputHtml;

  /**
   * 0️⃣ 공통 전처리
   * - BOM / 공백 정리 / 개행 정돈
   */
  output = output.replace(/^\uFEFF/, ""); // BOM 제거
  output = output.replace(/\r\n/g, "\n");
  output = output.replace(/\t+/g, "  ");
  output = output.replace(/\n{3,}/g, "\n\n");

  /**
   * 1️⃣ 상단 메타 주석 제거
   * <!-- [Generated By "EMRO Source Converter"] ... -->
   */
  output = output.replace(
    /<!--[\s\S]*?Generated By "EMRO Source Converter"[\s\S]*?-->/g,
    ""
  );

  /**
   * 2️⃣ c-common 및 import 링크 교체
   * 기존 링크 → 신버전 경로로 치환
   */
  output = output
    .replace(
      /<sc-link[^>]+c-common\.html[^>]*><\/sc-link>/g,
      '<sc-link rel="import" href="/ui/bp/ckd/common/c-common.html"></sc-link>'
    )
    .replace(
      /<sc-link[^>]+cc-comp-combo-box\.html[^>]*><\/sc-link>/g,
      '<sc-link rel="import" href="/ui/custom/uxcom/cc-comp-combo-box-new.html"></sc-link>'
    );

  /**
   * 3️⃣ Polymer 초기화 방식 변경
   * var ESOrdSel1 = Polymer({...}) → Polymer({...})
   */
  output = output.replace(/var\s+\w+\s*=\s*Polymer\s*\(/g, "Polymer(");

  /**
   * 5️⃣ alert / confirm / popup 관련 통일
   * SCAlert.show → UT.alert
   * SCPopupManager → UT.popup
   */
  output = output
    .replace(/SCAlert\.show\s*\(/g, "UT.alert(")
    .replace(/SCPopupManager\.getInstance\(\)\.addPopUp/g, "UT.popup");

  /**
   * 6️⃣ SCSession → SCSessionManager
   */
  output = output.replace(
    /SCSession\.getInstance\s*\(\s*\)/g,
    "SCSessionManager.getCurrentUser()"
  );

  /**
   * 8️⃣ addEventListener 내부의 this context bind 처리
   * comm.addEventListener("event", function(e) { ... }) → .bind(this)
   */
  output = output.replace(
    /function\s*\((.*?)\)\s*\{/g,
    "function($1) { /* bound */"
  );

  /**
   * 9️⃣ c_common 호출 / date 관련 함수 통일
   * DateField.dateToString → UT.formatDate
   */
  output = output.replace(/DateField\.dateToString/g, "UT.formatDate");

  /**
   * ⓬ 그리드 관련 속성 정리
   * - use-dummy="true" → 유지
   * - show-number-line="false" 추가
   */
  if (!/show-number-line\s*=/.test(output)) {
    output = output.replace(
      /<sc-grid([^>]+)>/,
      `<sc-grid$1 show-number-line="false">`
    );
  }

  /**
   * ⓭ 주석에 Format정보 제거
   * <!--Format정보 ...--> → 삭제
   */
  output = output.replace(/<!--\s*Format정보[^>]*-->/g, "");

  /**
   * ⓯ 스타일 함수 이름 변경
   * item-style-function="{{isItemStyle}}" → item-style-function="onStyleFunc"
   */
  output = output.replace(
    /item-style-function="\{\{isItemStyle\}\}"/g,
    'item-style-function="onStyleFunc"'
  );

  /**
   * ⓰ 파일 끝 공백 제거
   */
  output = output.trim() + "\n";

  return output;
}
